#!/usr/bin/env sh

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap




# global settings
# yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse off
# yabai -m config window_origin_display default
# yabai -m config window_placement second_child
# #yabai -m config window_topmost on
# yabai -m config window_shadow on
# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.90
# yabai -m config window_border off
# yabai -m config window_border_width 6
# yabai -m config active_window_border_color 0xff775759
# yabai -m config normal_window_border_color 0xff555555
# yabai -m config insert_feedback_color 0xffd75f5f
# yabai -m config split_ratio 0.50
# yabai -m config auto_balance off
# yabai -m config mouse_modifier alt
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap

# # general space settings
# yabai -m config layout bsp
# yabai -m config top_padding 15
# yabai -m config bottom_padding 15
# yabai -m config left_padding 15
# # NOTE: for OBS floating head
# # yabai -m config left_padding                 450
# yabai -m config right_padding 15
# yabai -m config window_gap 15

# apps to not manage (ignore)
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^VMWare Fusion$" manage=off

# change padding for single window on big screen
#yabai -m signal 	--add event=window_destroyed 	action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_focused 		action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_created 		action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_moved 		action="$HOME/.config/yabai/padding.sh"

echo "yabai configuration loaded.."

