#!/usr/bin/env sh

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
	external_bar                 off:40:0       \
	menubar_opacity              1.0            \
	mouse_follows_focus          off            \
	focus_follows_mouse          off            \
	window_origin_display        default        \
	window_placement             second_child   \
	window_zoom_persist          on             \
	window_shadow                on             \
	window_animation_duration    0.0            \
	window_opacity_duration      0.0            \
	active_window_opacity        1.0            \
	normal_window_opacity        0.90           \
	window_opacity               off            \
	insert_feedback_color        0xffd75f5f     \
	split_ratio                  0.50           \
	split_type                   auto           \
	auto_balance                 off            \
	top_padding                  12             \
	bottom_padding               12             \
	left_padding                 12             \
	right_padding                12             \
	window_gap                   06             \
	layout                       bsp            \
	mouse_modifier               alt            \
	mouse_action1                move           \
	mouse_action2                resize         \
	mouse_drop_action            swap



# apps to not manage (ignore)
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^VMWare Fusion$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off


# change padding for single window on big screen
#yabai -m signal 	--add event=window_destroyed 	action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_focused 		action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_created 		action="$HOME/.config/yabai/padding.sh"
#yabai -m signal 	--add event=window_moved 		action="$HOME/.config/yabai/padding.sh"
#

#yabai -m signal --add event=window_created action='
#	yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || \
#	yabai -m window $YABAI_WINDOW_ID --toggle float && \
#	yabai -m window $YABAI_WINDOW_ID --layer above
#  '
	#yabai -m window $YABAI_WINDOW_ID --grid 3:3:1:1:1:1

echo "yabai configuration loaded.."

