# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0c0b0c"

# Main text color
theme[main_fg]="#FAFCFB"

# Title color for boxes
theme[title]="#87a9b0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b59790"

# Background color of selected item in processes box
theme[selected_bg]="#6B5E73"

# Foreground color of selected item in processes box
theme[selected_fg]="#FAFCFB"

# Color of inactive/disabled text
theme[inactive_fg]="#584e51"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#87a9b0"

# Box outline and divider line color
theme[cpu_box]="#87a9b0"
theme[mem_box]="#87a9b0"
theme[net_box]="#87a9b0"
theme[proc_box]="#87a9b0"
theme[div_line]="#584e51"

# Gradient for all meters and graphs
theme[temp_start]="#87a9b0"
theme[temp_mid]="#b59790"
theme[temp_end]="#c38b7b"


theme[cpu_start]="#87a9b0"
theme[cpu_mid]="#a5a0b6"
theme[cpu_end]="#c38b7b"


theme[free_start]="#87a9b0"
theme[free_mid]="#c4d8e2"
theme[free_end]="#c4d8e2"


theme[cached_start]="#a5a0b6"
theme[cached_mid]="#a5a0b6"
theme[cached_end]="#a5a0b6"


theme[available_start]="#b59790"
theme[available_mid]="#b59790"
theme[available_end]="#b59790"


theme[used_start]="#c38b7b"
theme[used_mid]="#c38b7b"
theme[used_end]="#c38b7b"


theme[download_start]="#87a9b0"
theme[download_mid]="#a5a0b6"
theme[download_end]="#c4d8e2"


theme[upload_start]="#c38b7b"
theme[upload_mid]="#b59790"
theme[upload_end]="#a5a0b6"
