"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 10
command_timeout = 200
add_newline = true
right_format = """$cmd_duration"""
format = "$aws\n[$directory$git_branch$git_status]($style)$character"

[line_break]
disabled = false

[character]
error_symbol = "[󰩈](red) "
vicmd_symbol = "[](green)"

[cmd_duration]
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45_000
min_time = 500
format = '[ ⏱  $duration]($style)'
style = "yellow"

[directory]
read_only = " "
truncation_symbol = "…/"
style = "bold lavender"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[hg_branch]
symbol = " "

[git_commit]
disabled = false

[git_branch]
disabled = false
symbol = " "
format = "[$symbol$branch]($style) "
#format = "[\\[$symbol$branch\\]]($style)"
#ignore_branches = ["master", "main"]

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style)'
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
disabled = false
format = '[$all_status]($style)'
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""

# trigger tmux reload when using gitmux
# in tmux status bar
#[custom.tmux]
#command = 'tmux refresh-client -S >/dev/null 2>&1 &'
#detect_folders = ['.git']
#disabled = true

[aws]
format = '[$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

[azure]
disabled = true

[buf]
disabled = true
symbol = " "

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true
symbol = " "

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true
symbol = " "

[deno]
disabled = true

[docker_context]
symbol = " "
disabled = true

[dotnet]
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[gcloud]
disabled = true

[golang]
symbol = " "
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
symbol = " "
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
symbol = " "
disabled = true

[jobs]
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
disabled = true
#symbol = ""
symbol = "🤖 "
format = "[\\[$symbol($version)\\]]($style)"
style = "green"

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
symbol = " "
disabled = true

[perl]
disabled = true
symbol = " "

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true
python_binary = 'python3'

[ruby]
disabled = true

[rust]
disabled = true
symbol = " "

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true


[status]
style = "red"
symbol = "✗ "
map_symbol = true
success_symbol = ""
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
disabled = true

[swift]
disabled = true
symbol = " "

[terraform]
disabled = true
symbol = " "

[username]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true
